### ISSUE TITLE
Getting Fatal error: Uncaught Error: Class 'Firebase\JWT\ExpiredException' 

### ISSUE THREAD

**Issue by LalitBitcot** [GriffinLedingham/php-apple-signin#20]
hello,

downloaded this project then update composer
and add testing code on new file index.php

require_once 'Vendor/autoload.php';
use AppleSignIn\ASDecoder;

$identityToken = " <id_token>";
$appleSignInPayload = ASDecoder::getAppleSignInPayload($identityToken);
print_r($appleSignInPayload);

but i getting some fatal error - 

Fatal error: Uncaught Error: Class 'Firebase\JWT\ExpiredException' not found in D:\xampp\htdocs\folder\php-apple-signin-master\Vendor\JWT.php:138 Stack trace: #0 D:\xampp\htdocs\folder\php-apple-signin-master\ASDecoder.php(46): AppleSignIn\Vendor\JWT::decode('eyJraWQiOiJlWGF...', '-----BEGIN PUBL...', Array) #1 D:\xampp\htdocs\folder\php-apple-signin-master\ASDecoder.php(28): AppleSignIn\ASDecoder::decodeIdentityToken('eyJraWQiOiJlWGF...') #2 D:\xampp\htdocs\folder\php-apple-signin-master\index.php(10): AppleSignIn\ASDecoder::getAppleSignInPayload('eyJraWQiOiJlWGF...') #3 {main} thrown in D:\xampp\htdocs\folder\php-apple-signin-master\Vendor\JWT.php on line 138

Please help!

**Comment by dennissch** [comment]
install dependency packages:
$ php composer.phar require firebase/php-jwt 

Best, Dennis
